import type { Metadata } from "next";
import { GlobalEventProvider } from "~/common/components/global-event-provider";
import { GlobalNavigationBar } from "~/common/ui/global-navigation-bar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="flex flex-col h-screen overflow-hidden">
        <GlobalEventProvider />
        <GlobalNavigationBar />
        <main className="flex-grow overflow-hidden">{children}</main>
      </body>
    </html>
  );
}
