import type { Metadata } from "next";
import { GlobalNavigationBar } from "~/common/ui/global-navigation-bar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={``}>
        <GlobalNavigationBar />
        {children}
      </body>
    </html>
  );
}
